#!/usr/bin/env ruby

$stack = []

=begin
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/logging-1.8.0/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/nokogiri-1.5.5/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/pg-0.11.0/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/pg-0.11.0/ext
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/active_attr-0.5.1/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/net-sftp-2.0.5/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/zip-2.0.2/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/interfaces-2.3.0/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/ruby-gsm-1.1.0/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/luhnar-1.0.1/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/gsm2-2.1.1/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/graph_builder-1.0.1/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/range_builder-1.0.2/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/diff-lcs-1.1.3/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/little-plugger-1.1.3/lib
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/i18n-0.6.1/lib
=end
hermes_pathes = %w( 
/home/hermes/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/hermes-1.0.0/lib
)

module MyRequire

  def require file
    $stack.push file
    from = Time.now 
    indent = "  "*$stack.size
    result = super
    secs = Time.now - from
    puts "#{indent}#{file} #{secs} secs"
    $stack.pop
    result
  end
end

Object.class_eval { include MyRequire }
Module.class_eval { include MyRequire }

@prev = Module.constants

def show_constants
  now = Module.constants
  puts (now - @prev).sort
  @prev = now
end

def my_require what
  from = Time.now 
  print "requiring #{what} .... "
  require what
  secs = Time.now - from
  puts " #{secs} secs"
  #show_constants
end

require File.expand_path('../application', __FILE__)
require 'rubygems'
#gem 'hermes', version: '=1.0.0'

hermes_pathes.reverse.each {|p| $:.unshift p }
puts $:

my_require 'hermes'
my_require 'yaml'

exit
puts $:
puts Hermes::Logging
puts Hermes::Logging.logger progname: 'a', logname: 'mist'
puts Time.now

class A < Init::Application

  def logger 
    @logger ||= begin 
      require 'hermes'
      Hermes::Logging.logger progname: progname, logname: 'mist'
    end
  end

  def call
    while !stop_requested? 
      logger.info 'from a...'
      sleep 1
    end 
  end

  def stop
    logger.info 'stopped a...'
  end
end

A.new.command
